### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by dsifford** [dsifford/slackhist#4]

**Comment by Benoit99** [comment]
I was trying to use the executable as I don't have go. When I run the executable I briefly see a window pop up on my screen and it quickly disappears. The only file I downloaded was the executable as I wasn't sure what to do with the other files. Am I missing a step? Thanks.

**Comment by dsifford** [comment]
@Benoit99 What OS are you attempting to run it on?

**Comment by Benoit99** [comment]
Sorry for the late reply. I'm on Windows 10.

**Comment by dsifford** [comment]
@Benoit99 The windows executable needs to be ran from the command prompt. So, assuming the path to the file is `C:\slackhist.exe`, you'd need to run `C:\slackhist.exe <name-of-zip-file>.zip` to generate the xlsx file in the current directory.

**Comment by Benoit99** [comment]
![slack hist error 5-3-2017 3-35-32 pm](https://cloud.githubusercontent.com/assets/26845906/25678071/7aec5802-3016-11e7-8fd9-d918aad69318.jpg)
Here is a screenshot of what I am seeing. After entering the command it just returns and says "panic:"

**Comment by dsifford** [comment]
@Benoit99 Can you try running `slackhist.exe help` and see if you get a panic?

**Comment by dsifford** [comment]
I don't have a windows machine so I'm not able to try it myself

**Comment by Benoit99** [comment]
![image](https://cloud.githubusercontent.com/assets/26845906/25678311/4d97342a-3017-11e7-8b14-15d2267c3e0d.png)
that seems to do something

**Comment by dsifford** [comment]
@Benoit99 I think I know what's wrong. Windows is sometimes weird about file extensions. Can you try `slackhist.exe export.zip.zip` and see if that works?

(This is assuming you have a file named `export.zip` in the working directory)

**Comment by Benoit99** [comment]
I don't yet have a file name called export.zip. I thought the app would create the zip. Just for good measure, I tried again and got "panic" again.
![image](https://cloud.githubusercontent.com/assets/26845906/25687678/3d81ef06-3046-11e7-9128-bf378218c77c.png)

**Comment by dsifford** [comment]
Ah, no sorry about the confusion. You first have to [export the history](https://get.slack.help/hc/en-us/articles/201658943-Export-your-team-s-Slack-history) from your slack account (which saves a JSON dump of the entire history and zips it).

Once you download the export to your machine, rename it to `export.zip` (or something easy to type) and navigate to the directory you save it in the command prompt and run `slackhist.exe export.zip`.. That will produce the xlsx files from the zip file.

Hope that helps.

**Comment by Benoit99** [comment]
Yes, Thanks Much!
